language: java
sudo: true
jdk: oraclejdk12

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
    # Decrypt credentials tar and write output as non-enc
    - openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ];
        then rm -rf $HOME/google-cloud-sdk;
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
        curl https://sdk.cloud.google.com | bash;
      fi
    # Add gcloud to $PATH
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version
    - tar -xzf credentials.tar.gz
    - gcloud auth activate-service-account --key-file client-secret.json
    - chmod +x mvnw

install:
  - gcloud config set project $PROJECT_ID

#script:
#  - if [ "$TRAVIS_BRANCH" == "master" ];
#      then bash mvn_setup.sh;
#      gcloud endpoints services deploy target/openapi-docs/openapi.json;
#      mvn appengine:deploy;
#    fi
