# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - gatech-rest

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'gatech-rest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_01892e0fd72e41699b762654d5c2b037 }}
        package: '${{ github.workspace }}/target/*.jar'